### ISSUE TITLE
Video tutorial to complement the existing instructions

### ISSUE THREAD

**Issue by BPcoderepository** [MarkEdmondson1234/Shiny-R-SaaS#5]
Hello,

first of all thank you very much for this guide! 
I am asking whether you could make a video with further explanations on how to create this SaaS based on Shiny including the steps you mentioned.

For non-programmers (but having expertise in R and RShiny) like me, this could be really helpful to comprehend the ideas behind the coding. 

Stay safe and kind regards from Germany,
Max

**Comment by MarkEdmondson1234** [comment]
Thanks! I will consider doing a video when I next update it. It's been a while now and perhaps better ways to approach it.

**Comment by BPcoderepository** [comment]
That would be awesome!
