### ISSUE TITLE
Is firebase email/pass auth still working?

### ISSUE THREAD

**Issue by jcrodriguez1989** [MarkEdmondson1234/Shiny-R-SaaS#9]
I am using [GCP's Identity Platform](https://cloud.google.com/security/products/identity-platform), which is based on firebase.
However, when trying to login, I input the email and it automatically prompts to the "Create Account" option (but the user already exists, it then fails saying it that the user already exists).
Any thoughts? Which auth alternatives do you recommend nowadays?
Thank you very much Mark!

**Comment by MarkEdmondson1234** [comment]
Have you tried John’s Firebase package? https://firebase.john-coene.com/guide/get-started/

**Comment by jcrodriguez1989** [comment]
Yup, that's the one used in this repo ♥️.
but I can not get it to work on the login part of an already existing user.
In case you have no alternatives you are currently using, feel free to close this issue. I really appreciate your reply, Mark!
Thanks!

**Comment by MarkEdmondson1234** [comment]
Oh heh didn’t remember I ported it over.

**Comment by jcrodriguez1989** [comment]
Thanks for your replies 🫶🏼
